[package]
name = "spl1"
version = "0.1.0"
authors = ["o.korienev <o.korienev@smartweb.com.ua>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
